layout_spectrum: 0.6576942
typography_spectrum: 0.7097135
color:
  saturation: 0.3934792
  lightness: 0.9937689
  brandStrength: 0.1160683
  rhythmicContrast: 0.5409546
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Brightman
